### ISSUE TITLE
你也是17年才接触前端的吗

### ISSUE THREAD

**Issue by fooyee** [xiaohesong/TIL#22]
感谢库主的分享，仓库内容挺细致的。
不过我有个问题，看你这个仓库貌似是建于17年中下旬。难道你学前端两年不到吗？

**Comment by xiaohesong** [comment]
说来惭愧，也不算吧。之前写后端的，也会写前端。不过以前用的技术比较low。
逻辑处理基本都是jquery一把梭。再用下backbone的模板。
系统学习前端的确是在17年中下旬。
